blank_issues_enabled: false
contact_links:
  - name: Argantiu Discord
    url: https://crazycloudcraft.de/dc
    about: Our support Discord, please ask questions and search support here.
  - name: Creator Pack Wiki
    url: https://github.com/Argantiu/creatorsmodpack/wiki
    about: Take a look at the wiki page for instructions how to use the Modpack.
